version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./ssl/:/etc/letsencrypt/:ro
      - ./www/:/home/www/:ro
      - ./www/log/:/home/www/log/:rw
      # NOTE In fact only the following two folders used.
      # Add whole folder of `./www` is for convenience when adding a new site.
      #- ./www/demo.com/public:/home/www/demo.com/public:ro
      #- ./www/demo.com/.well-known:/home/www/demo.com/.well-known:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./ssl/:/etc/letsencrypt/:rw
      - ./www/:/home/www/:rw
      # NOTE Similar with `volumes` in `nginx`.
      #- ./www/demo.com/.well-known:/home/www/demo.com/.well-known:rw
